blank_issues_enabled: false
contact_links:
  - name: Security Policy
    url: https://github.com/rochdi4k/TFJ-TacMed-ReactNative/security/policy
    about: Read the security policy before reporting security or safety issues.
